ALTER TABLE planeten
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY,
MODIFY COLUMN naam VARCHAR(50) NOT NULL,
MODIFY COLUMN diameter INT NOT NULL,
MODIFY COLUMN afstand INT NOT NULL,
MODIFY COLUMN massa FLOAT NOT NULL;

INSERT INTO planeten (naam, diameter, afstand, massa, bezoek_datum)
VALUES ('Mars', 6779, 227900000, 0.107, '2023-01-05');